version: 2

updates:
  - package-ecosystem: composer
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '06:00'
      timezone: America/New_York
    groups:
      composer-minor-and-patch:
        update-types: [minor, patch]
    commit-message:
      prefix: 'chore(deps)'
      include: scope

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '06:00'
      timezone: America/New_York
    groups:
      actions-minor-and-patch:
        update-types: [minor, patch]
    commit-message:
      prefix: 'chore(actions)'
      include: scope
